### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [mskhokhar/fsp-medium#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Hi Manraj, thank you for your database schema.

A lot of work still need to be done regarding it. Please go over the checklist step-by-step and reconfigure your schema for it to be presented accordingly. 

Some comments I had at first sight are: 

- Add indexed and unique regarding the appropriate columns 
- created_at, modified_at for the columns (instead of date_created and date_updated). Correct data type is datetime I believe.
- Some primary keys are missing. e.g: comments table
- If you are going to have a lot of images on your app, it is better to use AWS rather than have an image_path column inside your posts
- session_token is missing on your users table 

Feel free to ping me if you have any confusions.

**Comment by mskhokhar** [comment]
I have tried to fix according to each and every point. Can you please review it. Thanks !

**Comment by linakherchi** [comment]
Primary keys are missing on the followers and post_collections tables.

**Comment by mskhokhar** [comment]
Required changes done!
