### ISSUE TITLE
Frontend routes

### ISSUE THREAD

**Issue by linakherchi** [mskhokhar/fsp-medium#4]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
1. splash will be instead `/`
2.Is the profile component the user profile page ? Can you explain to me why it is inside `/posts`. Thanks !

**Comment by mskhokhar** [comment]
Requirements are fulfilled
